# Generated by Django 2.2.6 on 2019-10-28 18:37

import TaskManager.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, max_length=255, null=True, upload_to=TaskManager.helpers.get_attachment_path)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_due', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='medium', max_length=6)),
                ('completed', models.BooleanField(default=False)),
                ('comment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='TaskManager.TaskComments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_due'],
            },
        ),
    ]
