# Generated by Django 2.2.6 on 2019-10-28 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_auto_20191029_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomments',
            name='ckpt_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
